POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Unite Sumittt1",
    "details": "Um evento ara quem é apaixonado por programação",
    "maximumAttendees": 1
}

###


POST http://localhost:3333/events/b6263535-5084-4e1e-8b63-5c6437a4f805/attendees
Content-Type: application/json

{
    "name": "Unite Sumittt1",
    "email": "gabriel@gmail.com",
}