POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "1234",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/48d51dea-5baa-40e2-b583-f9f27d9e1705/attendees
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego2@rocketseat.com.br"
}

###

GET http://localhost:3333/events/81a3f6db-45bf-4a6f-b10c-bcaf8837ac43

###

GET http://localhost:3333/attendees/1/badge
###

GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/48d51dea-5baa-40e2-b583-f9f27d9e1705/attendees?query=diego